#!/bin/bash

echo "sleepling"

echo 1

echo "udpate file"


echo "########################"
echo "check commit 1"
git rev-parse HEAD


echo "udpate file"
echo 1234 >> test.file


echo "########################"
git status

echo "########################"

#add file
git add .
#get last commit msg
lastmsg=`git log -1 --pretty=%B`
#ammend file
#git commit --amend  -m "NewVersion $ntag,  $lastmsg"
git commit   -m "NewVersion $ntag,  $lastmsg"

echo "########################"
echo "check commit 1"
git rev-parse HEAD



echo "########################"
git status
echo "########################"
#elif [ -f ".lock" ]; then
#echo 111
#git tag $ntag
#rm .lock
#fi


sleep 5
